### ISSUE TITLE
com.xkcoding.http.exception.SimpleHttpException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out

### ISSUE THREAD

**Issue by bobolau** [xkcoding/simple-http#5]
在JustAuth中报错timeout。
com.xkcoding.http.HttpUtil 创建的http实现内中都写死timeout为3000导致集成国外第三方网站全部超时，建议提供timeout参数供配置。

错误日志：
2020-04-25 16:57:35 http-nio-8085-exec-2 me.zhyd.oauth.log.Log(error:45) [ERROR] - Failed to login with oauth authorization.
com.xkcoding.http.exception.SimpleHttpException: java.net.http.HttpConnectTimeoutException: HTTP connect timed out
	at com.xkcoding.http.support.java11.HttpClientImpl.exec(HttpClientImpl.java:56)
	at com.xkcoding.http.support.java11.HttpClientImpl.post(HttpClientImpl.java:169)
	at com.xkcoding.http.support.java11.HttpClientImpl.post(HttpClientImpl.java:141)
	at com.xkcoding.http.support.java11.HttpClientImpl.post(HttpClientImpl.java:128)
	at com.xkcoding.http.HttpUtil.post(HttpUtil.java:120)
	at me.zhyd.oauth.request.AuthDefaultRequest.doPostAuthorizationCode(AuthDefaultRequest.java:213)
	at me.zhyd.oauth.request.AuthGithubRequest.getAccessToken(AuthGithubRequest.java:34)
	at me.zhyd.oauth.request.AuthDefaultRequest.login(AuthDefaultRequest.java:79)
	at org.openmall.mall.portal.ums.controller.RestAuthController.login(RestAuthController.java:48)

对应需要修改代码：
com.xkcoding.http.HttpUtil
static {
        Http defaultProxy = null;
        ClassLoader classLoader = HttpUtil.class.getClassLoader();
        if (ClassUtil.isPresent("java.net.http.HttpClient", classLoader)) {
            defaultProxy = new HttpClientImpl();
        } else if (ClassUtil.isPresent("okhttp3.OkHttpClient", classLoader)) {
            defaultProxy = new OkHttp3Impl();
        } else if (ClassUtil.isPresent("org.apache.http.impl.client.HttpClients", classLoader)) {
            defaultProxy = new com.xkcoding.http.support.httpclient.HttpClientImpl();
        } else if (ClassUtil.isPresent("cn.hutool.http.HttpRequest", classLoader)) {
            defaultProxy = new HutoolImpl();
        }

        proxy = (Http)defaultProxy;
    }

HttpClientImpl:
    public HttpClientImpl() {
        this(HttpClient.newBuilder().connectTimeout(Duration.ofMillis(3000L)).build());
    }

OkHttp3Impl:
public OkHttp3Impl() {
        this((new OkHttpClient()).newBuilder().connectTimeout(Duration.ofMillis(3000L)).writeTimeout(Duration.ofMillis(3000L)).readTimeout(Duration.ofMillis(3000L)).build());
    }

HutoolImpl:
 request = request.timeout(3000);

**Comment by xkcoding** [comment]
快照版本已经支持自定义超时时间，后续测试稳定之后，会发布正式版本
